### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by MissSpooks** [Royal-Rebels/Royal-Rebels#314] opened 2016-01-17 15:44 UTC
~~The End isn't resetting~~
Website and server do not recognize players voting on the first two links
Only owners and advisers can use the rejuv books
~~Remove exploding arrows
Remove arrows plugin
Villager breeding
Owners can only have 5 warps~~
Players can change spawners

**Comment by triarry** [comment] 2016-01-17 18:16
The End - Current problem with Multiverse, will check for update. Problem is, once 1.9 comes out, we're never resetting the end again, anyway, so this is a rather low priority to me (especially since the next server progression isn't happening until 1.9)

Voting - Should be easy fix, will replace with new voting links if necessary.

Rejuvination book issue - Unsure of what is causing this, will look further

Remove arrows plugin - will be done swiftly.

Villager breeding - can be fixed at a worldguard level, but this is very hacky and manual. will look for a plugin that overrides the server command.

5 warps - gotta screw around with mywarp

**Comment by triarry** [comment] 2016-01-18 01:07
Closed as duplicate of #316, #318, #319, #320

**Closed by triarry** 2016-01-18 01:07 UTC
